package com.ideal.spdb.system.to;

import com.ideal.spdb.utils.BaseModel;

/**
 * 
 * <p>Title:  浦发五星项目</p>
 * <p>Description:系统运行日志数据传输对象</p>
 * <p>Company: 上海理想信息产业(集团)有限公司</p>
 * @author dinghui
 * create date: 2012-2-27
 * @version 1.0
 */
public class PbLogSystemRunTO extends BaseModel{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String inSystemId;//生成序列规则设置（1：接入子系统；2：队列管理子系统；3：监控管理子系统）
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.LOG_SYSTEM_RUN_ID
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String logSystemRunId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.TYPE
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.LOG_DATETIME
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String logDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.FUNCTION_NAME
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.STEP_SEQ
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String stepSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.TERMINAL_NO
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String terminalNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.OPERTION_DESC
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String opertionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.RESULT
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.OTHOR_DESC
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String othorDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.REMARK
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PF_LOG_SYSTEM_RUN.LOG_SOURCE
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    private String logSource;
    
    
    public String getInSystemId() {
		return inSystemId;
	}

	public void setInSystemId(String inSystemId) {
		this.inSystemId = super.filter(inSystemId);
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.LOG_SYSTEM_RUN_ID
     *
     * @return the value of PF_LOG_SYSTEM_RUN.LOG_SYSTEM_RUN_ID
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getLogSystemRunId() {
        return logSystemRunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.LOG_SYSTEM_RUN_ID
     *
     * @param logSystemRunId the value for PF_LOG_SYSTEM_RUN.LOG_SYSTEM_RUN_ID
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setLogSystemRunId(String logSystemRunId) {
        this.logSystemRunId = super.filter(logSystemRunId);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.TYPE
     *
     * @return the value of PF_LOG_SYSTEM_RUN.TYPE
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.TYPE
     *
     * @param type the value for PF_LOG_SYSTEM_RUN.TYPE
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setType(String type) {
        this.type = super.filter(type);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.LOG_DATETIME
     *
     * @return the value of PF_LOG_SYSTEM_RUN.LOG_DATETIME
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getLogDatetime() {
        return logDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.LOG_DATETIME
     *
     * @param logDatetime the value for PF_LOG_SYSTEM_RUN.LOG_DATETIME
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setLogDatetime(String logDatetime) {
        this.logDatetime = super.filter(logDatetime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.FUNCTION_NAME
     *
     * @return the value of PF_LOG_SYSTEM_RUN.FUNCTION_NAME
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.FUNCTION_NAME
     *
     * @param functionName the value for PF_LOG_SYSTEM_RUN.FUNCTION_NAME
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setFunctionName(String functionName) {
        this.functionName = super.filter(functionName);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.STEP_SEQ
     *
     * @return the value of PF_LOG_SYSTEM_RUN.STEP_SEQ
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getStepSeq() {
        return stepSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.STEP_SEQ
     *
     * @param stepSeq the value for PF_LOG_SYSTEM_RUN.STEP_SEQ
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setStepSeq(String stepSeq) {
        this.stepSeq = super.filter(stepSeq);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.TERMINAL_NO
     *
     * @return the value of PF_LOG_SYSTEM_RUN.TERMINAL_NO
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getTerminalNo() {
        return terminalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.TERMINAL_NO
     *
     * @param terminalNo the value for PF_LOG_SYSTEM_RUN.TERMINAL_NO
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setTerminalNo(String terminalNo) {
        this.terminalNo = super.filter(terminalNo);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.OPERTION_DESC
     *
     * @return the value of PF_LOG_SYSTEM_RUN.OPERTION_DESC
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getOpertionDesc() {
        return opertionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.OPERTION_DESC
     *
     * @param opertionDesc the value for PF_LOG_SYSTEM_RUN.OPERTION_DESC
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setOpertionDesc(String opertionDesc) {
        this.opertionDesc = super.filter(opertionDesc);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.RESULT
     *
     * @return the value of PF_LOG_SYSTEM_RUN.RESULT
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.RESULT
     *
     * @param result the value for PF_LOG_SYSTEM_RUN.RESULT
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setResult(String result) {
        this.result = super.filter(result);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.OTHOR_DESC
     *
     * @return the value of PF_LOG_SYSTEM_RUN.OTHOR_DESC
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getOthorDesc() {
        return othorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.OTHOR_DESC
     *
     * @param othorDesc the value for PF_LOG_SYSTEM_RUN.OTHOR_DESC
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setOthorDesc(String othorDesc) {
        this.othorDesc = super.filter(othorDesc);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.REMARK
     *
     * @return the value of PF_LOG_SYSTEM_RUN.REMARK
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.REMARK
     *
     * @param remark the value for PF_LOG_SYSTEM_RUN.REMARK
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = super.filter(remark);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PF_LOG_SYSTEM_RUN.LOG_SOURCE
     *
     * @return the value of PF_LOG_SYSTEM_RUN.LOG_SOURCE
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public String getLogSource() {
        return logSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PF_LOG_SYSTEM_RUN.LOG_SOURCE
     *
     * @param logSource the value for PF_LOG_SYSTEM_RUN.LOG_SOURCE
     *
     * @mbggenerated Mon Feb 27 10:08:33 CST 2012
     */
    public void setLogSource(String logSource) {
        this.logSource = super.filter(logSource);
    }
}